# Generated by Django 5.1.1 on 2024-10-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=4)),
            ],
        ),
    ]
